import re
import unittest
from pathlib import Path


REQUIRED_ENV_VARS = {
    "TRADINGBUFFETT_RESULTS_DIR",
    "TRADINGBUFFETT_CACHE_DIR",
    "TRADINGBUFFETT_MEMORY_LOG_PATH",
    "TRADINGBUFFETT_LLM_PROVIDER",
    "TRADINGBUFFETT_OPENAI_API_KEY",
    "TRADINGBUFFETT_OPENAI_USE_LOCAL",
    "TRADINGBUFFETT_OPENAI_BASE_URL",
    "TRADINGBUFFETT_OPENAI_EMBEDDING_MODEL",
    "TRADINGBUFFETT_GOOGLE_API_KEY",
    "TRADINGBUFFETT_ANTHROPIC_API_KEY",
    "TRADINGBUFFETT_XAI_API_KEY",
    "TRADINGBUFFETT_MINIMAX_API_KEY",
    "TRADINGBUFFETT_DEEPSEEK_API_KEY",
    "TRADINGBUFFETT_DASHSCOPE_API_KEY",
    "TRADINGBUFFETT_ZHIPU_API_KEY",
    "TRADINGBUFFETT_OPENROUTER_API_KEY",
    "TRADINGBUFFETT_AZURE_OPENAI_API_KEY",
    "TRADINGBUFFETT_AZURE_OPENAI_ENDPOINT",
    "TRADINGBUFFETT_AZURE_OPENAI_DEPLOYMENT_NAME",
    "TRADINGBUFFETT_AZURE_OPENAI_API_VERSION",
    "TRADINGBUFFETT_ALPACA_API_KEY",
    "TRADINGBUFFETT_ALPACA_SECRET_KEY",
    "TRADINGBUFFETT_ALPACA_BASE_URL",
    "TRADINGBUFFETT_ALPACA_PAPER_BASE_URL",
    "TRADINGBUFFETT_ALPACA_USE_PAPER",
    "TRADINGBUFFETT_ALPACA_READ_ONLY",
    "TRADINGBUFFETT_FINNHUB_API_KEY",
    "TRADINGBUFFETT_FRED_API_KEY",
    "TRADINGBUFFETT_COINDESK_API_KEY",
    "TRADINGBUFFETT_ALPHA_VANTAGE_API_KEY",
}


class EnvSampleTests(unittest.TestCase):
    def test_env_sample_documents_required_runtime_keys(self):
        sample = Path("env.sample").read_text(encoding="utf-8")
        documented = set(re.findall(r"^([A-Z][A-Z0-9_]*)=", sample, flags=re.MULTILINE))

        self.assertFalse(
            REQUIRED_ENV_VARS - documented,
            f"env.sample is missing: {sorted(REQUIRED_ENV_VARS - documented)}",
        )


if __name__ == "__main__":
    unittest.main()
